version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - backend
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx/
    depends_on:
      - api

  api:
    build:
      args:
        user: danilo
        uid: 1000
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: api
    networks:
      - backend
      - db
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: client_host=172.17.0.1
      PHP_IDE_CONFIG: serverName=localhost
    depends_on:
      - database

  database:
    image: mariadb
    container_name: database
    expose:
      - 3306
    ports:
      - "3306:3306"
    networks:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD=PASS_ROOT
      - MYSQL_USER=USER_DB
      - MYSQL_PASSWORD=PASS_DB
      - MYSQL_DATABASE=NAME_DB
    volumes:
      - ./runtime/db:/var/lib/mysql

networks:
  backend:
  db:
