version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - backend
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx/
    depends_on:
      - api

  api:
    build: ./docker/php
    container_name: api
    networks:
      - backend
      - db
    volumes:
      - ./:/var/www/html
    depends_on:
      - database

  database:
    image: mariadb
    container_name: database
    expose:
      - 3306
    ports:
      - "3306:3306"
    networks:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD=api123
      - MYSQL_USER=api
      - MYSQL_PASSWORD=api123
      - MYSQL_DATABASE=formula_tg
    volumes:
      - ./runtime/db:/var/lib/mysql

networks:
  backend:
  db: